# Generated by Django 5.0 on 2023-12-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tittle_tag',
            field=models.CharField(default='Рецепты', max_length=50),
        ),
    ]
