# Generated by Django 5.0 on 2023-12-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0002_post_tittle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tittle_tag',
        ),
    ]
