# Generated by Django 5.0 on 2023-12-27 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0003_remove_post_tittle_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
