# Generated by Django 5.0 on 2023-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0004_post_recipe_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
