# Generated by Django 5.0 on 2023-12-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0005_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.TextField(verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe_tittle',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
