# Generated by Django 5.0 on 2024-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecipe', '0006_remove_post_author_post_image_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
